LDSCRIPT_PATH=../ldscripts
SW_VERSION_PATH=../sw_version.h
SEC_CONFIG_PATH=../../../../../utilities/python_scripts/secure_image/

.PHONY: generate_ldscripts FORCE

FORCE:

generate_ldscripts : mem.ld sections.ld

%.ld : $(LDSCRIPT_PATH)/%.ld.h FORCE
	"$(CC)" -I "$(BSP_CONFIG_DIR)" -I "$(MIDDLEWARE_CONFIG_DIR)" $(PRE_BUILD_EXTRA_DEFS) -imacros "$(APP_CONFIG_H)" $(LD_DEFS) -Ddg_configDEVICE=$(DEVICE) -E -P -c "$<" -o "$(BUILD_OUTPUT_DIR)/$@"

%.img: %.bin
	@echo 'Invoking: Mkimage Prepare SUOTA Image'
	"$(PYTHON)" "$(SCRIPT)" -q -p "$(REVISION)" --sw_version "$(SW_VERSION_PATH)" $(BUILD_OUTPUT_DIR)/$< $(BUILD_OUTPUT_DIR)/$@
	@echo ' '

%_secure.img: %.bin
	if [ -f $(SEC_CONFIG_PATH)secure_cfg.xml ] && [ -f $(SEC_CONFIG_PATH)product_keys.xml ]; then \
		echo 'Invoking: Mkimage Prepare Secure SUOTA Image';\
		"$(PYTHON)" "$(SCRIPT)" -q -p "$(REVISION)" --sw_version "$(SW_VERSION_PATH)" -s "$(SEC_CONFIG_PATH)secure_cfg.xml" --prod_keys "$(SEC_CONFIG_PATH)product_keys.xml" $< $(BUILD_OUTPUT_DIR)/$@; \
		fi
	@echo ' '
